# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarea',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='adminarea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='adminarea',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at'),
        ),
    ]
