# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhdb', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('model_pk', models.CharField(blank=True, max_length=128, null=True)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('W', 'Waiting Approval'), ('A', 'Accepted'), ('R', 'Rejected'), ('X', 'Flagged as never to show (contains inappropriate content / spam)'), ('E', 'Error occurred trying to approve this suggestion'), ('D', 'Error: Primary instance is missing or duplicate')], default='W', max_length=2)),
                ('action', models.CharField(choices=[('DR', 'Remove a relationship'), ('CR', 'Create a relationship'), ('UR', 'Update a relationship'), ('DM', 'Delete entry'), ('CM', 'Create entry'), ('UM', 'Update entry')], default='CM', max_length=128)),
                ('is_hidden', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('DELETE', 'DELETE'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=128)),
                ('data', models.TextField(blank=True, null=True)),
                ('suggestDate', models.DateField(auto_now_add=True)),
                ('approvalDate', models.DateField(blank=True, null=True)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=256)),
                ('upload', models.FileField(blank=True, max_length=256, null=True, upload_to='suggestions')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggest.Suggest')),
            ],
        ),
        migrations.AddField(
            model_name='affectedinstance',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggest.Suggest'),
        ),
    ]
