# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:17
from __future__ import unicode_literals

# import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("geo", "__first__")]

    operations = [
        migrations.CreateModel(
            name="ExcelDownloadFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            (b"PP", b"Freshman"),
                            (b"RE", b"Sophomore"),
                            (b"IN", b"Junior"),
                            (b"OT", b"Senior"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "purposeother",
                    models.CharField(max_length=150, verbose_name="Other purpose"),
                ),
                ("referralurl", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_tet",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_pt",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_ind",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "fongtilid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name=b"Org. ID (Fongtil)"
                    ),
                ),
                (
                    "justiceid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name=b"Org. ID (Min. Justice)"
                    ),
                ),
                (
                    "stafffulltime",
                    models.IntegerField(
                        blank=True, null=True, verbose_name=b"Full time staff"
                    ),
                ),
                (
                    "staffparttime",
                    models.IntegerField(
                        blank=True, null=True, verbose_name=b"Part time staff"
                    ),
                ),
                ("verified", models.DateField(auto_now=True, null=True)),
                (
                    "phoneprimary",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name=b"Phone"
                    ),
                ),
                (
                    "phonesecondary",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name=b"Alternate phone",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                ("fax", models.CharField(blank=True, max_length=64, null=True)),
                ("web", models.CharField(blank=True, max_length=64, null=True)),
                ("facebook", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="OrganizationClass",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        verbose_name=b"Code",
                    ),
                ),
                ("orgtype", models.CharField(max_length=150, verbose_name=b"Type")),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationPlace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=256, null=True)),
                ("email", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nhdb.Organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("email", models.CharField(blank=True, max_length=64, null=True)),
                ("verified", models.DateField(auto_now=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nhdb.Organization",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_tet",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pt",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_ind",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "description_tet",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "description_pt",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "description_ind",
                    models.TextField(
                        blank=True, null=True, verbose_name="Project Description"
                    ),
                ),
                (
                    "startdate",
                    models.DateField(blank=True, null=True, verbose_name=b"Start date"),
                ),
                (
                    "enddate",
                    models.DateField(blank=True, null=True, verbose_name=b"End date"),
                ),
                ("verified", models.DateField(auto_now=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("notes_tet", models.TextField(blank=True, null=True)),
                ("notes_en", models.TextField(blank=True, null=True)),
                ("notes_pt", models.TextField(blank=True, null=True)),
                ("notes_ind", models.TextField(blank=True, null=True)),
                (
                    "stafffulltime",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Full time staff"
                    ),
                ),
                (
                    "staffparttime",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Part time staff"
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=b"projectimage/%Y%m%d/"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhdb.Project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Notes about this relationship",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nhdb.Organization",
                    ),
                ),
            ],
            options={"verbose_name": "Project to Organization link"},
        ),
        migrations.CreateModel(
            name="ProjectOrganizationClass",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("verified", models.DateField(auto_now=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhdb.Person"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhdb.Project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectPlace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.AdminArea"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhdb.Project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_tet", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_pt", models.CharField(max_length=255, null=True)),
                ("name_ind", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
                ("description_tet", models.CharField(max_length=255, null=True)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("description_pt", models.CharField(max_length=255, null=True)),
                ("description_ind", models.CharField(max_length=255, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RecordOwner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="projectorganization",
            name="organizationclass",
            field=models.ForeignKey(
                default=b"P",
                on_delete=django.db.models.deletion.CASCADE,
                to="nhdb.ProjectOrganizationClass",
                verbose_name="Organization involvement",
            ),
        ),
        migrations.AddField(
            model_name="projectorganization",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nhdb.Project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="activity",
            field=models.ManyToManyField(
                blank=True, related_name="project_activity", to="nhdb.PropertyTag"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="beneficiary",
            field=models.ManyToManyField(
                blank=True, related_name="project_beneficiary", to="nhdb.PropertyTag"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ManyToManyField(
                blank=True, through="nhdb.ProjectOrganization", to="nhdb.Organization"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="person",
            field=models.ManyToManyField(
                blank=True, through="nhdb.ProjectPerson", to="nhdb.Person"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="place",
            field=models.ManyToManyField(
                blank=True, through="nhdb.ProjectPlace", to="geo.AdminArea"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="projecttype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nhdb.ProjectType",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sector",
            field=models.ManyToManyField(
                blank=True, related_name="project_sector", to="nhdb.PropertyTag"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                default=b"A",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nhdb.ProjectStatus",
                verbose_name=b"Status",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="orgtype",
            field=models.ForeignKey(
                default=b"LNGO",
                on_delete=django.db.models.deletion.CASCADE,
                to="nhdb.OrganizationClass",
                verbose_name="class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectplace", unique_together=set([("project", "place")])
        ),
        migrations.AlterUniqueTogether(
            name="projectperson", unique_together=set([("person", "project")])
        ),
        migrations.AlterUniqueTogether(
            name="projectorganization",
            unique_together=set([("project", "organization")]),
        ),
    ]
