# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:20
from __future__ import unicode_literals

from django.db import migrations

def sql():
    models = (
        'organization',
        'organizationclass',
        'organizationplace',
        'organizationplacedescription',
        'person',
        'project',
        'projectimage',
        'projectorganization',
        'projectorganizationclass',
        'projectperson',
        'projectplace',
        'projectstatus',
        'projecttype',
        'propertytag'
    )
    template = 'UPDATE nhdb_{} SET created_at = NOW();'
    return '\n'.join([template.format(m) for m in models])

class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0002_timestamps'),
    ]

    operations = [
        migrations.RunSQL(sql())
    ]
