# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0003_delete_tempexceldownloadfeedback'),
    ]

    operations = [

        migrations.CreateModel(
            name='ExcelDownloadFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('purpose', models.CharField(choices=[(b'PP', b'Freshman'), (b'RE', b'Sophomore'), (b'IN', b'Junior'), (b'OT', b'Senior')], max_length=2)),
                ('purposeother', models.CharField(max_length=150, verbose_name='Other purpose')),
                ('referralurl', models.CharField(max_length=256)),
            ],
        ),

        migrations.AddField(
            model_name='exceldownloadfeedback',
            name='organization',
            field=models.CharField(default='None', max_length=150, verbose_name='organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exceldownloadfeedback',
            name='purpose',
            field=models.CharField(choices=[(b'PP', b'Project planning'), (b'RE', b'Research'), (b'IN', b'Personal interest'), (b'OT', b'Other (please specify)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='exceldownloadfeedback',
            name='purposeother',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Other purpose'),
        ),
        migrations.AlterField(
            model_name='exceldownloadfeedback',
            name='referralurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_ind',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_tet',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
