# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0004_split_propertytag'),
    ]

    operations = [
       migrations.RunSQL(
           '''
           INSERT INTO nhdb_activity (name, description)
  SELECT
  jsonb_strip_nulls(jsonb_build_object(
                        'en', "name_en", 'pt', "name_pt", 'ind', "name_ind", 'tet', "name_tet"
                    )),
  jsonb_strip_nulls(jsonb_build_object(
                        'en', "description_en", 'pt', "description_pt", 'ind',
                        "description_ind", 'tet', "description_tet"
                    ))
FROM nhdb_propertytag
WHERE path ILIKE 'ACT.%';

INSERT INTO nhdb_sector (name, description)
  SELECT
  jsonb_strip_nulls(jsonb_build_object(
                        'en', "name_en", 'pt', "name_pt", 'ind', "name_ind", 'tet', "name_tet"
                    )),
  jsonb_strip_nulls(jsonb_build_object(
                        'en', "description_en", 'pt', "description_pt", 'ind',
                        "description_ind", 'tet', "description_tet"
                    ))
FROM nhdb_propertytag
WHERE path ILIKE 'INV.%';


INSERT INTO nhdb_beneficiary (name, description)
  SELECT
  jsonb_strip_nulls(jsonb_build_object(
                        'en', "name_en", 'pt', "name_pt", 'ind', "name_ind", 'tet', "name_tet"
                    )),
  jsonb_strip_nulls(jsonb_build_object(
                        'en', "description_en", 'pt', "description_pt", 'ind',
                        "description_ind", 'tet', "description_tet"
                    ))
FROM nhdb_propertytag
WHERE path ILIKE 'BEN.%';
           '''
       )
    ]
