# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '__first__'),
        ('nhdb', '0005_person_primary_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='primary_contact',
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='suco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Suco'),
        ),
    ]
