# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("nhdb", "0007_auto_20160610_0629")]

    operations = [
        migrations.RemoveField(model_name="organizationplacedescription", name="id"),
        migrations.AlterField(
            model_name="organizationplacedescription",
            name="organizationplace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="nhdb.OrganizationPlace",
            ),
        ),
    ]
