# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0007_auto_20171008_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.ManyToManyField(blank=True, to='nhdb.Activity'),
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiary',
            field=models.ManyToManyField(blank=True, to='nhdb.Beneficiary'),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ManyToManyField(blank=True, to='nhdb.Sector'),
        )
    ]
