# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("nhdb", "0008_auto_20160610_0630")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="primary_contact_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_contact_person",
                to="nhdb.Organization",
            ),
        )
    ]
