# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0008_auto_20171008_1421'),
    ]

    operations = [

        migrations.RunSQL(
            """
INSERT INTO nhdb_project_beneficiary (project_id, beneficiary_id)
SELECT project_id,
  nhdb_beneficiary.id
FROM
  nhdb_project_oldbeneficiary
  LEFT JOIN nhdb_propertytag ON nhdb_propertytag.id = nhdb_project_oldbeneficiary.propertytag_id
  LEFT JOIN nhdb_beneficiary ON nhdb_beneficiary.name #>> '{en}' = nhdb_propertytag.name
  WHERE nhdb_beneficiary.id IS NOT NULL;


INSERT INTO nhdb_project_activity (project_id, activity_id)
SELECT project_id,
  nhdb_activity.id
FROM
  nhdb_project_oldactivity
  LEFT JOIN nhdb_propertytag ON nhdb_propertytag.id = nhdb_project_oldactivity.propertytag_id
  LEFT JOIN nhdb_activity ON nhdb_activity.name #>> '{en}' = nhdb_propertytag.name
  WHERE nhdb_activity.id IS NOT NULL;



INSERT INTO nhdb_project_sector (project_id, sector_id)
SELECT project_id,
  nhdb_sector.id
FROM
  nhdb_project_oldsector
  LEFT JOIN nhdb_propertytag ON nhdb_propertytag.id = nhdb_project_oldsector.propertytag_id
  LEFT JOIN nhdb_sector ON nhdb_sector.name #>> '{en}' = nhdb_propertytag.name
  WHERE nhdb_sector.id IS NOT NULL;
            """)
    ]
