# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0009_auto_20171008_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='oldactivity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='oldbeneficiary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='oldsector',
        ),
    ]
