# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0009_person_primary_contact_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='organizationplacedescription',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='organizationplacedescription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='organizationplacedescription',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projectorganization',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projectorganization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projectorganization',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projectorganizationclass',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projectorganizationclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projectorganizationclass',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projectperson',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projectperson',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projectperson',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projectplace',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projectplace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projectplace',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='recordowner',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='recordowner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='recordowner',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='exceldownloadfeedback',
            name='purpose',
            field=models.CharField(choices=[('PP', 'Project planning'), ('RE', 'Research'), ('IN', 'Personal interest'), ('OT', 'Other (please specify)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fongtilid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Org. ID (Fongtil)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='justiceid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Org. ID (Min. Justice)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgtype',
            field=models.ForeignKey(default='LNGO', on_delete=django.db.models.deletion.CASCADE, to='nhdb.OrganizationClass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phoneprimary',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phonesecondary',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Alternate phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stafffulltime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Full time staff'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='staffparttime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Part time staff'),
        ),
        migrations.AlterField(
            model_name='organizationclass',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='organizationclass',
            name='orgtype',
            field=models.CharField(max_length=150, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.CASCADE, to='nhdb.ProjectStatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projectimage/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='projectorganization',
            name='organizationclass',
            field=models.ForeignKey(default='P', on_delete=django.db.models.deletion.CASCADE, to='nhdb.ProjectOrganizationClass', verbose_name='Organization involvement'),
        ),
    ]
