# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0010_auto_20171008_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='names',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
