# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0010_timestamp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytag',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='propertytag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='propertytag',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='updated at'),
        ),
    ]
