# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """
    Translated names -> a JSON field
    """

    dependencies = [
        ('nhdb', '0011_project_names'),
    ]

    operations = [
        migrations.RunSQL(
            '''UPDATE nhdb_project SET names = JSON_STRIP_NULLS(
                JSON_BUILD_OBJECT('en', name_en, 'tet', name_tet, 'pt', name_pt, 'ind', name_ind)
            )
            '''
        )
    ]
