# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0012_json_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_ind',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_tet',
        ),
    ]
