# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhdb', '0013_auto_20171101_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='names',
            new_name='name',
        ),
    ]
