db:
  build: .
  environment:
    - POSTGRES_PASSWORD=L1terary20@
    - POSTGRES_USER=django
    - POSTGRES_DB=timordata.info
  volumes:
    - dbteststore:/var/lib/postgresql/data
  ports:
    - "5432"
  command: ["postgres"]
