BEGIN;
TRUNCATE "library_version_beneficiary", "nhdb_project_beneficiary", "auth_permission", "auth_group", "donormapping_fundingsurveyinfomethods", "geo_worldsimple", "nhdb_project_sector", "auth_user_user_permissions", "library_version_tag", "social_auth_nonce", "suggest_affectedinstance", "donormapping_fundingofferdocument", "donormapping_fundingoffer_beneficiary", "donormapping_fundingoffer", "donormapping_fundingsurvey_fundingrecvrel", "nhdb_projecttype", "geo_world", "datatrans_fieldwordcount", "reversion_version", "geo_subdistrict", "nhdb_projectimage", "nhdb_projectplace", "django_content_type", "django_session", "auth_user_groups", "nhdb_organization", "nhdb_organizationclass", "nhdb_organizationplace", "geo_suco", "donormapping_fundingoffer_district", "geo_town", "geo_adminarea", "library_version_activity", "library_tag", "donormapping_fundingoffer_sector", "donormapping_fundingoffer_activity", "library_version", "nhdb_project", "django_admin_log", "library_version_sector", "library_publication_organization", "auth_group_permissions", "library_publication_location", "library_publication_country", "library_publication", "geo_road", "donormapping_fundingsurvey_fundinggiverel", "nhdb_person", "donormapping_fundingsurvey", "nhdb_recordowner", "nhdb_projectperson", "nhdb_projectorganizationclass", "nhdb_propertytag", "thumbnail_kvstore", "django_select2_keymap", "nhdb_projectstatus", "geo_placealternate", "social_auth_usersocialauth", "donormapping_fundingsurvey_properties", "donormapping_donorannouncement", "library_pubtype", "nhdb_project_activity", "nhdb_projectorganization", "datatrans_modelwordcount", "suggest_suggest", "donormapping_donorsurveyresponse", "social_auth_association", "social_auth_code", "library_author", "geo_district", "library_publication_author", "datatrans_keyvalue", "auth_user", "reversion_revision";
SELECT setval(pg_get_serial_sequence('"django_admin_log"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_permission"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_group"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"auth_user"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_content_type"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"datatrans_keyvalue"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"datatrans_modelwordcount"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"datatrans_fieldwordcount"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"reversion_revision"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"reversion_version"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"social_auth_usersocialauth"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"social_auth_nonce"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"social_auth_association"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"social_auth_code"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"django_select2_keymap"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"donormapping_fundingoffer"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"donormapping_fundingofferdocument"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"donormapping_donorannouncement"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"donormapping_donorsurveyresponse"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"donormapping_fundingsurveyinfomethods"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"donormapping_fundingsurvey"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"library_publication"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"library_tag"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"library_version"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"library_author"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_organization"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_person"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_propertytag"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_projecttype"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_recordowner"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_projectimage"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_project"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_projectorganization"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_projectperson"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_projectplace"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"nhdb_organizationplace"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"geo_town"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"geo_road"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"geo_world"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"geo_worldsimple"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"geo_placealternate"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"suggest_affectedinstance"','id'), 1, false);
SELECT setval(pg_get_serial_sequence('"suggest_suggest"','id'), 1, false);

COMMIT;
