CREATE EXTENSION postgis;
-- CREATE ROLE belun LOGIN SUPERUSER PASSWORD 'L1terary20@';
CREATE ROLE django LOGIN SUPERUSER PASSWORD 'L1terary20@';
-- CREATE DATABASE gis;


-- CREATE ROLE josh LOGIN SUPERUSER;

-- CREATE DATABASE "timordata.info";
